name: Compile kmod-tun for Redmi AX3000

on:
  workflow_dispatch:  # 允许手动触发
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/compile-kmod-tun.yml'  # 只有这个文件变化时才触发

jobs:
  compile:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
        gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev \
        file wget zstd

    - name: Update feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Configure for Redmi AX3000
      run: |
        echo "CONFIG_TARGET_qualcommax=y" > .config
        echo "CONFIG_TARGET_qualcommax_ipq50xx=y" >> .config
        echo "CONFIG_TARGET_qualcommax_ipq50xx_DEVICE_redmi_ax3000=y" >> .config
        echo "CONFIG_PACKAGE_kmod-tun=m" >> .config
        make defconfig

    - name: Compile kmod-tun only
      run: |
        make package/kmod-tun/compile -j$(nproc) V=s

    - name: Find and upload kmod-tun package
      uses: actions/upload-artifact@v4
      with:
        name: kmod-tun-package
        path: |
          bin/targets/qualcommax/ipq50xx/packages/kmod-tun*.ipk
          bin/packages/arm_cortex-a7/kernel/kmod-tun*.ipk
        if-no-files-found: error
