name: Build TUN support for Redmi AX3000

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: immortalwrt/immortalwrt
        ref: openwrt-24.10
        submodules: true

    - name: Setup build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison g++ gawk \
        gettext git libncurses5-dev libssl-dev python3 python3-dev \
        rsync unzip zlib1g-dev file wget

    - name: Configure for device
      run: |
        echo "CONFIG_TARGET_qualcommax=y" > .config
        echo "CONFIG_TARGET_qualcommax_ipq50xx=y" >> .config
        echo "CONFIG_TARGET_qualcommax_ipq50xx_DEVICE_redmi_ax3000=y" >> .config
        echo "CONFIG_KERNEL_TUN=y" >> .config
        make defconfig

    - name: Build firmware
      run: |
        echo "=== 开始编译固件 ==="
        make -j$(nproc) V=s 2>&1 | tail -50

    - name: List generated files
      run: |
        echo "=== 生成的文件列表 ==="
        find bin/ -name "*.bin" -o -name "*.itb" -o -name "*.ubi" | head -10
        echo "=== 文件详情 ==="
        ls -la bin/targets/qualcommax/ipq50xx/ || echo "目录不存在"
        echo "=== 文件大小 ==="
        du -h bin/targets/qualcommax/ipq50xx/*.bin 2>/dev/null || echo "未找到bin文件"

    - name: Upload firmware artifacts
      uses: actions/upload-artifact@v4
      with:
        name: redmi-ax3000-firmware
        path: bin/targets/qualcommax/ipq50xx/*.bin
        if-no-files-found: error

    - name: Upload all artifacts
      uses: actions/upload-artifact@v4
      with:
        name: all-build-files
        path: bin/targets/qualcommax/ipq50xx/
        if-no-files-found: warn
