name: Enable TUN in Kernel for Redmi AX3000

on:
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
    - name: Checkout the exact repository
      uses: actions/checkout@v4
      with:
        repository: kmiit/Redmi_AX3000_immortalwrt
        submodules: true

    - name: Setup build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison g++ gawk \
        gettext git libncurses5-dev libssl-dev python3-full python3-dev \
        rsync unzip zlib1g-dev file wget zstd

    - name: Update and install feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Configure base system
      run: |
        echo "CONFIG_TARGET_qualcommax=y" > .config
        echo "CONFIG_TARGET_qualcommax_ipq50xx=y" >> .config
        echo "CONFIG_TARGET_qualcommax_ipq50xx_DEVICE_redmi_ax3000=y" >> .config
        make defconfig

    - name: Modify the generic kernel config
      run: |
        echo "=== 修改通用内核配置文件 ==="
        GENERIC_CONFIG="target/linux/generic/config-6.6"
        
        if [ ! -f "$GENERIC_CONFIG" ]; then
            echo "错误：未找到 $GENERIC_CONFIG"
            find target/linux -name "config-6.6" | head -5
            exit 1
        fi
        
        echo "修改配置文件: $GENERIC_CONFIG"
        
        # 备份原配置
        cp "$GENERIC_CONFIG" "${GENERIC_CONFIG}.backup"
        
        # 修改 TUN 配置
        sed -i 's/# CONFIG_TUN is not set/CONFIG_TUN=y/' "$GENERIC_CONFIG"
        sed -i 's/# CONFIG_TUN_VNET_CROSS_LE is not set/CONFIG_TUN_VNET_CROSS_LE=y/' "$GENERIC_CONFIG"
        
        echo "=== 修改后的配置 ==="
        grep "CONFIG_TUN" "$GENERIC_CONFIG"

    - name: Force clean and reconfigure
      run: |
        # 彻底清理并重新配置
        rm -f .config
        make target/linux/clean
        echo "CONFIG_TARGET_qualcommax=y" > .config
        echo "CONFIG_TARGET_qualcommax_ipq50xx=y" >> .config
        echo "CONFIG_TARGET_qualcommax_ipq50xx_DEVICE_redmi_ax3000=y" >> .config
        make defconfig

    - name: Verify configuration
      run: |
        echo "=== 最终配置验证 ==="
        echo "通用配置文件中的 TUN 配置:"
        grep "CONFIG_TUN" target/linux/generic/config-6.6
        
        echo "当前 .config 中的相关配置:"
        grep -i "tun\|TUN" .config || echo "在 .config 中未找到 TUN 配置"

    - name: Download and build
      run: |
        make download -j$(nproc)
        make toolchain/install -j$(nproc) V=s

    - name: Build kernel with TUN
      run: |
        echo "=== 编译包含 TUN 的内核 ==="
        make target/compile -j$(nproc) V=s 2>&1 | tail -20

    - name: Check for TUN module
      run: |
        echo "=== 检查 TUN 模块 ==="
        find build_dir/ -name "*tun*" -type f | head -5 || echo "未找到 TUN 相关文件"
        
        # 查看内核构建目录
        echo "内核构建目录:"
        find build_dir/ -name "linux-*" -type d | head -3

    - name: Complete the build
      run: |
        echo "=== 完成编译 ==="
        make -j$(nproc) V=s 2>&1 | tail -15

    - name: Prepare artifacts
      run: |
        echo "=== 生成的文件 ==="
        find bin/ -name "*.bin" -o -name "*.itb" -o -name "*.ubi" | head -5 || echo "未找到固件文件"
        
        # 特别查找 TUN 模块
        find build_dir/ -name "tun.ko" || echo "未找到 tun.ko"

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: redmi-ax3000-with-tun
        path: |
          bin/targets/qualcommax/ipq50xx/
        if-no-files-found: warn
