name: Compile kmod-tun for Redmi AX3000

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  compile:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
        gettext git libncurses5-dev libssl-dev python3-full python3-dev rsync unzip zlib1g-dev \
        file wget zstd

    - name: Update feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Find correct package name
      run: |
        # 搜索包含 tun 的内核模块包
        find . -name "*.mk" -exec grep -l "tun" {} \; | head -10
        echo "=== 搜索可能的包名 ==="
        ./scripts/feeds list | grep -i tun
        ./scripts/feeds list | grep -i kernel
        ls -la package/kernel/ | grep -i tun || true

    - name: Configure for Redmi AX3000
      run: |
        echo "CONFIG_TARGET_qualcommax=y" > .config
        echo "CONFIG_TARGET_qualcommax_ipq50xx=y" >> .config
        echo "CONFIG_TARGET_qualcommax_ipq50xx_DEVICE_redmi_ax3000=y" >> .config
        # 先不指定具体包，让 defconfig 来处理
        make defconfig

    - name: Search for tun in config
      run: |
        # 查看配置中与 tun 相关的选项
        grep -i tun .config || true
        make menuconfig 2>/dev/null || true

    - name: Try to compile kernel modules
      run: |
        # 尝试编译所有内核模块相关的包
        make package/kernel/linux/compile -j$(nproc) V=s
