name: Check Available Devices

on:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: immortalwrt/immortalwrt
        ref: openwrt-24.10
        submodules: true

    - name: List all qualcommax devices
      run: |
        echo "=== qualcommax 的所有设备配置 ==="
        # 查看 image Makefile 中的所有设备定义
        if [ -f "target/linux/qualcommax/image/Makefile" ]; then
            echo "=== Makefile 中的设备定义 ==="
            grep "define Device" target/linux/qualcommax/image/Makefile | head -20
            echo ""
            echo "=== 详细的设备配置 ==="
            grep -A 10 "define Device" target/linux/qualcommax/image/Makefile | head -30
        else
            echo "未找到 target/linux/qualcommax/image/Makefile"
            find target/linux/qualcommax -name "Makefile" | head -5
        fi

    - name: Check config files
      run: |
        echo "=== 配置文件检查 ==="
        # 查看配置选项
        find target/linux -name "Config.in" -exec grep -l "qualcommax" {} \; | head -3
        echo ""
        echo "=== 配置选项 ==="
        find target/linux -name "Config.in" -exec grep -A 3 -B 3 "qualcommax" {} \; | head -20

    - name: Check for Redmi AX3000
      run: |
        echo "=== 搜索 Redmi AX3000 ==="
        # 在整个代码库中搜索
        find . -name "*.mk" -o -name "*.in" -o -name "*.conf" | xargs grep -l "redmi\|ax3000\|xiaomi" 2>/dev/null | head -10 || echo "未找到相关配置"
