name: Build Firmware for Redmi AX3000 with TUN

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
    - name: Checkout custom repository
      uses: actions/checkout@v4
      with:
        repository: kmiit/Redmi_AX3000_immortalwrt
        submodules: true

    - name: Setup build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison g++ gawk \
        gettext git libncurses5-dev libssl-dev python3 python3-dev \
        rsync unzip zlib1g-dev file wget

    - name: Update and install feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Configure for Redmi AX3000
      run: |
        echo "=== 配置 Redmi AX3000 ==="
        # 使用这个仓库的配置（应该已经包含正确配置）
        make defconfig
        
        # 启用 TUN 支持
        echo "CONFIG_KERNEL_TUN=y" >> .config
        echo "CONFIG_KERNEL_TUN_VNET_CROSS_LE=y" >> .config
        make defconfig

    - name: Verify configuration
      run: |
        echo "=== 验证配置 ==="
        grep "CONFIG_TARGET" .config | head -5
        grep "CONFIG_KERNEL_TUN" .config || echo "TUN 配置未设置"
        echo "=== 设备配置 ==="
        grep "redmi\|ax3000" .config || echo "设备配置未找到"

    - name: Build firmware
      run: |
        echo "=== 开始编译固件 ==="
        make -j$(nproc) V=s 2>&1 | tail -50

    - name: Check generated files
      run: |
        echo "=== 检查生成的文件 ==="
        find bin/ -name "*.bin" -o -name "*.ubi" -o -name "*.itb" | head -10
        echo "=== 文件详情 ==="
        ls -la bin/targets/ */ 2>/dev/null | head -5 || echo "查看目录结构"
        du -h bin/targets/*/*/*.bin 2>/dev/null || echo "未找到bin文件"

    - name: Upload firmware artifacts
      uses: actions/upload-artifact@v4
      with:
        name: redmi-ax3000-firmware
        path: bin/targets/
        if-no-files-found: error

    - name: Final check
      run: |
        echo "=== 最终检查 ==="
        # 确保有文件生成
        if find bin/ -name "*.bin" | grep -q .; then
            echo "✅ 固件编译成功！"
            find bin/ -name "*.bin" | head -3
        else
            echo "❌ 未找到固件文件"
            echo "目录结构:"
            find bin/ -type d 2>/dev/null | head -10
            exit 1
        fi
