name: Compile TUN module for Redmi AX3000

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  compile:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
        gettext git libncurses5-dev libssl-dev python3-full python3-dev rsync unzip zlib1g-dev \
        file wget zstd

    - name: Update feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Find TUN-related packages
      run: |
        echo "=== 搜索所有包含 tun 的包 ==="
        find . -name "*.mk" -exec grep -l "tun\|TUN" {} \; | head -20
        echo ""
        echo "=== 在 feeds 中搜索 tun ==="
        ./scripts/feeds list | grep -i tun || true
        echo ""
        echo "=== 在 kernel 包中搜索 ==="
        find package/kernel/ -name "*" -type d | grep -i tun || true
        echo ""
        echo "=== 查看内核配置选项 ==="
        grep -i tun target/linux/*/config-* 2>/dev/null | head -10 || true

    - name: Configure for Redmi AX3000
      run: |
        echo "CONFIG_TARGET_qualcommax=y" > .config
        echo "CONFIG_TARGET_qualcommax_ipq50xx=y" >> .config
        echo "CONFIG_TARGET_qualcommax_ipq50xx_DEVICE_redmi_ax3000=y" >> .config
        # 先让系统自动配置，然后我们再手动启用 TUN
        make defconfig

    - name: Check kernel config for TUN
      run: |
        echo "=== 当前配置中与 TUN 相关的选项 ==="
        grep -i tun .config || echo "没有找到 TUN 相关配置"
        echo ""
        echo "=== 尝试在 menuconfig 中查找 ==="
        # 查看内核配置
        grep -n "TUN\|tun" target/linux/generic/config-* 2>/dev/null || true

    - name: Build toolchain and kernel
      run: |
        # 先编译工具链和内核
        make toolchain/install -j$(nproc)
        make target/compile -j$(nproc)
        make package/kernel/linux/compile -j$(nproc)

    - name: Search for built-in TUN support
      run: |
        echo "=== 检查内核是否内置了 TUN 支持 ==="
        # 查看编译好的内核配置
        find build_dir/ -name ".config" -exec grep -l "CONFIG_TUN" {} \; | head -5
        find build_dir/ -name ".config" -exec grep -H "CONFIG_TUN" {} \; | head -5 || true
