name: Compile kmod-tun for Redmi AX3000

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  compile:
    runs-on: ubuntu-latest
    timeout-minutes: 120  # 设置更长超时时间
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
        gettext git libncurses5-dev libssl-dev python3-full python3-dev rsync unzip zlib1g-dev \
        file wget zstd

    - name: Update feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Configure for Redmi AX3000
      run: |
        echo "CONFIG_TARGET_qualcommax=y" > .config
        echo "CONFIG_TARGET_qualcommax_ipq50xx=y" >> .config
        echo "CONFIG_TARGET_qualcommax_ipq50xx_DEVICE_redmi_ax3000=y" >> .config
        echo "CONFIG_PACKAGE_kmod-tun=m" >> .config
        make defconfig

    - name: Build toolchain first (关键步骤)
      run: |
        # 先编译工具链和主机工具
        make toolchain/install -j$(nproc) V=s
        make target/compile -j$(nproc) V=s

    - name: Build kernel modules
      run: |
        # 现在编译内核模块
        make package/kernel/linux/compile -j$(nproc) V=s

    - name: Build kmod-tun package
      run: |
        # 最后编译特定的包
        make package/feeds/packages/kmod-tun/compile -j$(nproc) V=s || \
        make package/kernel/kmod-tun/compile -j$(nproc) V=s || \
        make package/feeds/base/kmod-tun/compile -j$(nproc) V=s

    - name: Find and upload kmod-tun package
      uses: actions/upload-artifact@v4
      with:
        name: kmod-tun-package
        path: |
          bin/targets/qualcommax/ipq50xx/packages/kmod-tun*.ipk
          bin/packages/arm_cortex-a7/kernel/kmod-tun*.ipk
          build_dir/target-*/kmod-tun-*/ipkg-*/kmod-tun*.ipk
        if-no-files-found: warn
