name: Compile TUN module for Redmi AX3000

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  compile:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib \
        gettext git libncurses5-dev libssl-dev python3-full python3-dev rsync unzip zlib1g-dev \
        file wget zstd

    - name: Update feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Configure for Redmi AX3000 with TUN
      run: |
        echo "CONFIG_TARGET_qualcommax=y" > .config
        echo "CONFIG_TARGET_qualcommax_ipq50xx=y" >> .config
        echo "CONFIG_TARGET_qualcommax_ipq50xx_DEVICE_redmi_ax3000=y" >> .config
        echo "CONFIG_PACKAGE_kmod-tun=y" >> .config
        make defconfig

    - name: Verify TUN configuration
      run: |
        echo "=== 检查 TUN 配置 ==="
        grep "CONFIG_PACKAGE_kmod-tun" .config
        echo "=== 完整配置检查 ==="
        grep -i "tun\|TUN" .config || true

    - name: Download all sources first
      run: |
        make download -j$(nproc)

    - name: Build toolchain
      run: |
        make toolchain/install -j$(nproc) V=s

    - name: Build target and kernel
      run: |
        make target/compile -j$(nproc) V=s
        make package/kernel/linux/compile -j$(nproc) V=s

    - name: Try to find kmod-tun package location
      run: |
        echo "=== 查找 kmod-tun 包的位置 ==="
        find . -name "*kmod-tun*" -type d | head -10 || true
        find . -name "Makefile" -exec grep -l "kmod-tun" {} \; | head -5 || true
        ls -la package/feeds/ || true
        ls -la package/kernel/ || true

    - name: Build kmod-tun with debug info
      run: |
        # 尝试不同的可能路径
        make package/feeds/packages/kmod-tun/compile V=s 2>&1 | head -50 || \
        make package/kernel/kmod-tun/compile V=s 2>&1 | head -50 || \
        make package/feeds/base/kmod-tun/compile V=s 2>&1 | head -50 || \
        echo "尝试直接编译所有包来寻找 kmod-tun"
        make V=s 2>&1 | grep -A 10 -B 10 "kmod-tun" | head -30

    - name: Search for any compiled packages
      run: |
        echo "=== 搜索所有已编译的包 ==="
        find . -name "*.ipk" | head -20
        find . -name "*tun*" -type f | head -10
