name: Compile kmod-tun for Redmi AX3000

on:
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
    - name: Checkout the exact repository
      uses: actions/checkout@v4
      with:
        repository: kmiit/Redmi_AX3000_immortalwrt
        submodules: true

    - name: Setup build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison g++ gawk \
        gettext git libncurses5-dev libssl-dev python3-full python3-dev \
        rsync unzip zlib1g-dev file wget zstd

    - name: Update and install feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Configure for Redmi AX3000
      run: |
        # 使用与固件完全相同的配置
        echo "CONFIG_TARGET_qualcommax=y" > .config
        echo "CONFIG_TARGET_qualcommax_ipq50xx=y" >> .config
        echo "CONFIG_TARGET_qualcommax_ipq50xx_DEVICE_redmi_ax3000=y" >> .config
        echo "CONFIG_PACKAGE_kmod-tun=y" >> .config
        make defconfig

    - name: Verify kernel version match
      run: |
        echo "=== 确保内核版本匹配 ==="
        grep "LINUX_VERSION" .config
        grep "LINUX_KERNEL_" .config | head -5

    - name: Download all sources
      run: make download -j$(nproc)

    - name: Build toolchain
      run: make toolchain/install -j$(nproc) V=s

    - name: Build target and kernel
      run: |
        make target/compile -j$(nproc) V=s
        make package/kernel/linux/compile -j$(nproc) V=s

    - name: Build kmod-tun package
      run: make package/kmod-tun/compile -j$(nproc) V=s

    - name: Find and upload kmod-tun package
      uses: actions/upload-artifact@v4
      with:
        name: kmod-tun-redmi-ax3000
        path: |
          bin/targets/qualcommax/ipq50xx/packages/kmod-tun*.ipk
          bin/packages/aarch64_cortex-a53/kernel/kmod-tun*.ipk
        if-no-files-found: error

    - name: Show build info for verification
      run: |
        echo "=== 编译信息验证 ==="
        find bin/ -name "*.ipk" | head -5
        echo "=== 内核模块信息 ==="
        find build_dir/ -name "*.ko" | grep -i tun | head -3 || true
