name: Build kmod-tun for Redmi AX3000

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: immortalwrt/immortalwrt
        ref: openwrt-24.10
        submodules: true

    - name: Setup build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison g++ gawk \
        gettext git libncurses5-dev libssl-dev python3-full python3-dev \
        rsync unzip zlib1g-dev file wget zstd

    - name: Update feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Configure for exact device and kernel
      run: |
        echo "CONFIG_TARGET_qualcommax=y" > .config
        echo "CONFIG_TARGET_qualcommax_ipq50xx=y" >> .config
        echo "CONFIG_TARGET_qualcommax_ipq50xx_DEVICE_redmi_ax3000=y" >> .config
        echo "CONFIG_PACKAGE_kmod-tun=y" >> .config
        echo "CONFIG_KERNEL_TUN=y" >> .config
        make defconfig

    - name: Verify configuration
      run: |
        echo "=== 配置验证 ==="
        grep "CONFIG_TARGET" .config | head -5
        grep "CONFIG_PACKAGE_kmod-tun" .config
        grep "CONFIG_KERNEL_TUN" .config

    - name: Download only required sources
      run: |
        make package/kmod-tun/download V=s

    - name: Build kmod-tun only
      run: |
        echo "=== 开始编译 kmod-tun ==="
        make package/kmod-tun/compile -j$(nproc) V=s 2>&1 | tail -30

    - name: Find the kmod-tun package
      run: |
        echo "=== 查找生成的 kmod-tun 包 ==="
        find . -name "*kmod-tun*.ipk" | head -5 || echo "未找到 kmod-tun IPK 文件"
        
        # 详细搜索
        echo "=== 详细搜索 ==="
        find bin/ -name "*.ipk" | grep -i tun || find build_dir/ -name "*.ipk" | grep -i tun || echo "未找到任何 IPK 文件"
        
        # 查看构建目录
        echo "=== 构建目录内容 ==="
        ls -la bin/packages/ 2>/dev/null || true
        ls -la bin/targets/ 2>/dev/null || true

    - name: Extract package info
      run: |
        echo "=== 包信息 ==="
        # 查找所有可能的包位置
        find . -name "*kmod-tun*" -type f 2>/dev/null | head -10 || echo "未找到 kmod-tun 文件"

    - name: Upload kmod-tun package
      uses: actions/upload-artifact@v4
      with:
        name: kmod-tun-package
        path: |
          bin/packages/*/kmod-tun*.ipk
          bin/targets/*/packages/kmod-tun*.ipk
          build_dir/*/kmod-tun*/ipkg*/kmod-tun*.ipk
        if-no-files-found: error

    - name: Debug if failed
      if: failure()
      run: |
        echo "=== 调试信息 ==="
        echo "当前目录:"
        pwd
        ls -la
        echo "构建目录结构:"
        find . -name "kmod-tun*" -type d | head -5
        echo "Makefile 位置:"
        find . -name "Makefile" -exec grep -l "kmod-tun" {} \; | head -3
