name: Diagnose Build Issue

on:
  workflow_dispatch:

jobs:
  diagnose:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        repository: immortalwrt/immortalwrt
        ref: openwrt-24.10
        submodules: true

    - name: Setup environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git libncurses5-dev

    - name: Check directory structure
      run: |
        echo "=== 仓库结构 ==="
        ls -la
        echo "=== 目标目录结构 ==="
        find . -name "target" -type d | head -3
        find . -name "qualcommax" -type d | head -3
        echo "=== 配置文件 ==="
        find . -name "*.mk" -path "*/qualcommax/*" | head -5

    - name: Find device configuration
      run: |
        echo "=== 查找设备配置 ==="
        # 搜索 Redmi AX3000 配置
        find . -name "*.mk" -exec grep -l "redmi.*ax3000\|ax3000.*redmi" {} \; | head -5
        echo ""
        echo "=== 查看 Makefile ==="
        cat target/linux/qualcommax/image/Makefile | grep -A 5 -B 5 "redmi\|ax3000" || true

    - name: Try to configure
      run: |
        echo "=== 尝试配置 ==="
        # 查看可用的配置
        make help | grep "config" || true
        echo ""
        echo "=== 尝试列出配置 ==="
        make menuconfig 2>/dev/null || echo "menuconfig 不可用"
        echo ""
        echo "=== 直接查看配置选项 ==="
        find . -name "Config.in" -exec grep -l "qualcommax" {} \; | head -3

    - name: Build test
      run: |
        echo "=== 测试编译 ==="
        # 尝试一个简单的编译测试
        make tools/install || echo "工具编译失败"
        make toolchain/install || echo "工具链编译失败"
        
        echo "=== 检查编译环境 ==="
        ls -la staging_dir/ 2>/dev/null | head -3 || echo "staging_dir 不存在"
