name: Enable TUN in Kernel for Redmi AX3000

on:
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Setup build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison g++ gawk gettext git libncurses5-dev libssl-dev python3-full python3-dev rsync unzip zlib1g-dev file wget zstd

    - name: Update and install feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Modify kernel config for TUN
      run: |
        echo "=== Modifying kernel configuration ==="
        KERNEL_CONFIG="target/linux/generic/config-6.6"
        
        if [ -f "$KERNEL_CONFIG" ]; then
            echo "Enabling TUN in kernel config"
            sed -i 's/# CONFIG_TUN is not set/CONFIG_TUN=y/' "$KERNEL_CONFIG"
            sed -i 's/# CONFIG_TUN_VNET_CROSS_LE is not set/CONFIG_TUN_VNET_CROSS_LE=y/' "$KERNEL_CONFIG"
            echo "TUN configuration enabled"
        else
            echo "Kernel config file not found: $KERNEL_CONFIG"
            find target/linux -name "config-*" | head -5
        fi

    - name: Configure target
      run: |
        echo "CONFIG_TARGET_qualcommax=y" > .config
        echo "CONFIG_TARGET_qualcommax_ipq50xx=y" >> .config
        echo "CONFIG_TARGET_qualcommax_ipq50xx_DEVICE_redmi_ax3000=y" >> .config
        make defconfig

    - name: Download sources
      run: |
        make download -j$(nproc)

    - name: Build toolchain
      run: |
        make toolchain/install -j$(nproc) V=s

    - name: Build kernel
      run: |
        echo "=== Building kernel ==="
        make target/compile -j$(nproc) V=s 2>&1 | tail -20

    - name: Check for TUN module
      run: |
        echo "=== Checking for TUN module ==="
        find build_dir/ -name "*tun*" | head -10 || echo "No TUN files found"

    - name: Complete build
      run: |
        echo "=== Completing build ==="
        make -j$(nproc) V=s 2>&1 | tail -15

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: firmware-with-tun
        path: |
          bin/targets/qualcommax/ipq50xx/*.bin
          bin/targets/qualcommax/ipq50xx/*.itb
        if-no-files-found: ignore
