name: Enable TUN in Kernel for Redmi AX3000

on:
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
    - name: Checkout the exact repository
      uses: actions/checkout@v4
      with:
        repository: kmiit/Redmi_AX3000_immortalwrt
        submodules: true

    - name: Setup build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential clang flex bison g++ gawk \
        gettext git libncurses5-dev libssl-dev python3-full python3-dev \
        rsync unzip zlib1g-dev file wget zstd

    - name: Update and install feeds
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Configure base system
      run: |
        echo "CONFIG_TARGET_qualcommax=y" > .config
        echo "CONFIG_TARGET_qualcommax_ipq50xx=y" >> .config
        echo "CONFIG_TARGET_qualcommax_ipq50xx_DEVICE_redmi_ax3000=y" >> .config
        make defconfig

    - name: Find and modify the correct kernel config
      run: |
        echo "=== 查找正确的内核配置文件 ==="
        # 查找 qualcommax 架构的配置文件
        KERNEL_CONFIG=$(find target/linux/qualcommax -name "config-6.6" | head -1)
        
        if [ -z "$KERNEL_CONFIG" ]; then
            echo "未找到 qualcommax 的 config-6.6，尝试其他路径"
            KERNEL_CONFIG=$(find target/linux -name "config-6.6" | grep -v ramips | head -1)
        fi
        
        if [ -z "$KERNEL_CONFIG" ]; then
            echo "未找到任何 config-6.6 文件，列出所有配置:"
            find target/linux -name "config-*" | head -10
            exit 1
        fi
        
        echo "使用内核配置文件: $KERNEL_CONFIG"
        
        # 备份并修改配置
        cp "$KERNEL_CONFIG" "${KERNEL_CONFIG}.backup"
        sed -i 's/# CONFIG_TUN is not set/CONFIG_TUN=y/' "$KERNEL_CONFIG"
        sed -i 's/# CONFIG_TUN_VNET_CROSS_LE is not set/CONFIG_TUN_VNET_CROSS_LE=y/' "$KERNEL_CONFIG"
        
        echo "修改后的 TUN 配置:"
        grep "CONFIG_TUN" "$KERNEL_CONFIG"

    - name: Clean and reconfigure
      run: |
        make target/linux/clean
        make defconfig

    - name: Verify the configuration
      run: |
        echo "=== 验证配置 ==="
        # 检查配置是否正确应用
        grep -i "tun\|TUN" .config || echo "在 .config 中未找到 TUN 配置"
        
        # 检查内核配置
        find target/linux -name "config-6.6" -exec grep -l "CONFIG_TUN" {} \; | head -3
        find target/linux -name "config-6.6" -exec grep -h "CONFIG_TUN" {} \; | head -5

    - name: Download and build
      run: |
        make download -j$(nproc)
        make toolchain/install -j$(nproc)

    - name: Build the kernel
      run: |
        echo "=== 编译内核 ==="
        make target/compile -j$(nproc) V=s 2>&1 | tail -30

    - name: Check for built modules
      run: |
        echo "=== 检查编译的模块 ==="
        find build_dir/ -name "*.ko" | grep -i tun | head -5 || echo "未找到 TUN 模块"
        
        # 查看构建目录结构
        echo "构建目录内容:"
        ls -la build_dir/ 2>/dev/null | head -5 || true

    - name: Complete the build
      run: |
        echo "=== 完成编译 ==="
        make -j$(nproc) V=s 2>&1 | tail -20

    - name: Prepare artifacts
      run: |
        echo "=== 最终文件 ==="
        find bin/ -name "*.bin" -o -name "*.itb" -o -name "*.ubi" | head -5
        find build_dir/ -name "tun.ko" || echo "未找到 tun.ko"

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: redmi-ax3000-build
        path: |
          bin/targets/qualcommax/ipq50xx/
        if-no-files-found: warn
